import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface KeywordEntry {
  keyword: string;
  category: string;
  weight: number;
  aliases: string[];
}

const ROLE_KEYWORD_MAP: Record<string, KeywordEntry[]> = {
  'software-engineer': [
    // Languages
    { keyword: 'JavaScript', category: 'language', weight: 5, aliases: ['JS', 'ECMAScript'] },
    { keyword: 'TypeScript', category: 'language', weight: 5, aliases: ['TS'] },
    { keyword: 'Python', category: 'language', weight: 4, aliases: ['py'] },
    { keyword: 'Java', category: 'language', weight: 4, aliases: [] },
    { keyword: 'Go', category: 'language', weight: 3, aliases: ['Golang'] },
    { keyword: 'Rust', category: 'language', weight: 2, aliases: [] },
    { keyword: 'C#', category: 'language', weight: 3, aliases: ['CSharp', 'C Sharp'] },
    { keyword: 'C++', category: 'language', weight: 2, aliases: ['CPP'] },
    { keyword: 'Ruby', category: 'language', weight: 2, aliases: [] },
    { keyword: 'PHP', category: 'language', weight: 2, aliases: [] },
    { keyword: 'Kotlin', category: 'language', weight: 2, aliases: [] },
    { keyword: 'Swift', category: 'language', weight: 2, aliases: [] },
    { keyword: 'Scala', category: 'language', weight: 2, aliases: [] },
    { keyword: 'Shell Script', category: 'language', weight: 2, aliases: ['Bash', 'Shell'] },
    // Frameworks
    { keyword: 'React', category: 'framework', weight: 5, aliases: ['React.js', 'ReactJS'] },
    { keyword: 'Node.js', category: 'framework', weight: 5, aliases: ['Node', 'NodeJS'] },
    { keyword: 'Express', category: 'framework', weight: 4, aliases: ['Express.js'] },
    { keyword: 'Spring Boot', category: 'framework', weight: 4, aliases: ['Spring'] },
    { keyword: 'Django', category: 'framework', weight: 3, aliases: [] },
    { keyword: 'Flask', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'FastAPI', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'Next.js', category: 'framework', weight: 3, aliases: ['NextJS'] },
    { keyword: 'NestJS', category: 'framework', weight: 2, aliases: ['Nest.js'] },
    { keyword: 'GraphQL', category: 'framework', weight: 3, aliases: ['Apollo'] },
    { keyword: 'REST API', category: 'framework', weight: 5, aliases: ['RESTful', 'REST APIs'] },
    { keyword: 'gRPC', category: 'framework', weight: 2, aliases: [] },
    { keyword: '.NET Core', category: 'framework', weight: 3, aliases: ['.NET', 'DotNet'] },
    { keyword: 'Ruby on Rails', category: 'framework', weight: 2, aliases: ['Rails'] },
    // Tools
    { keyword: 'Docker', category: 'tool', weight: 5, aliases: ['Container'] },
    { keyword: 'Kubernetes', category: 'tool', weight: 3, aliases: ['K8s'] },
    { keyword: 'Git', category: 'tool', weight: 5, aliases: ['GitHub', 'GitLab', 'Version Control'] },
    { keyword: 'CI/CD', category: 'tool', weight: 4, aliases: ['Continuous Integration', 'Continuous Deployment'] },
    { keyword: 'Jenkins', category: 'tool', weight: 3, aliases: [] },
    { keyword: 'GitHub Actions', category: 'tool', weight: 2, aliases: ['GHA'] },
    { keyword: 'AWS', category: 'tool', weight: 4, aliases: ['Amazon Web Services'] },
    { keyword: 'Azure', category: 'tool', weight: 3, aliases: ['Microsoft Azure'] },
    { keyword: 'GCP', category: 'tool', weight: 3, aliases: ['Google Cloud', 'Google Cloud Platform'] },
    { keyword: 'Jira', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'Confluence', category: 'tool', weight: 1, aliases: [] },
    { keyword: 'Postman', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'Swagger', category: 'tool', weight: 2, aliases: ['OpenAPI'] },
    // Databases
    { keyword: 'PostgreSQL', category: 'database', weight: 5, aliases: ['Postgres'] },
    { keyword: 'MySQL', category: 'database', weight: 4, aliases: [] },
    { keyword: 'MongoDB', category: 'database', weight: 4, aliases: ['Mongo'] },
    { keyword: 'Redis', category: 'database', weight: 3, aliases: [] },
    { keyword: 'Elasticsearch', category: 'database', weight: 2, aliases: ['ES'] },
    { keyword: 'SQLite', category: 'database', weight: 2, aliases: [] },
    { keyword: 'DynamoDB', category: 'database', weight: 2, aliases: ['Dynamo'] },
    { keyword: 'Cassandra', category: 'database', weight: 2, aliases: [] },
    { keyword: 'SQL', category: 'database', weight: 5, aliases: ['Structured Query Language', 'Relational Database'] },
    { keyword: 'NoSQL', category: 'database', weight: 3, aliases: ['Non-relational'] },
    // Concepts
    { keyword: 'Microservices', category: 'concept', weight: 4, aliases: ['Micro-services'] },
    { keyword: 'System Design', category: 'concept', weight: 4, aliases: ['Architecture', 'Software Architecture'] },
    { keyword: 'Design Patterns', category: 'concept', weight: 3, aliases: ['OOP', 'Object-Oriented'] },
    { keyword: 'Algorithms', category: 'concept', weight: 3, aliases: ['Data Structures'] },
    { keyword: 'Testing', category: 'concept', weight: 4, aliases: ['Unit Test', 'Integration Test', 'E2E'] },
    { keyword: 'Code Review', category: 'concept', weight: 3, aliases: ['Peer Review'] },
    { keyword: 'API Design', category: 'concept', weight: 4, aliases: [] },
    { keyword: 'Performance Optimization', category: 'concept', weight: 3, aliases: ['Performance Tuning'] },
    { keyword: 'Caching', category: 'concept', weight: 3, aliases: ['Cache'] },
    { keyword: 'Authentication', category: 'concept', weight: 3, aliases: ['Auth', 'OAuth', 'JWT'] },
    { keyword: 'Authorization', category: 'concept', weight: 3, aliases: ['RBAC', 'Access Control'] },
    { keyword: 'Message Queue', category: 'concept', weight: 3, aliases: ['RabbitMQ', 'Kafka', 'Pub/Sub'] },
    { keyword: 'Event-Driven', category: 'concept', weight: 2, aliases: ['Event Sourcing'] },
    { keyword: 'WebSockets', category: 'concept', weight: 2, aliases: ['Socket.io'] },
    { keyword: 'Rate Limiting', category: 'concept', weight: 2, aliases: [] },
    { keyword: 'Load Balancing', category: 'concept', weight: 2, aliases: [] },
    { keyword: 'Scalability', category: 'concept', weight: 3, aliases: ['Scaling'] },
    { keyword: 'Security', category: 'concept', weight: 3, aliases: ['Application Security', 'Secure Coding'] },
    // Methodologies
    { keyword: 'Agile', category: 'methodology', weight: 3, aliases: ['Scrum', 'Sprint'] },
    { keyword: 'TDD', category: 'methodology', weight: 3, aliases: ['Test-Driven Development'] },
    { keyword: 'CI/CD Pipeline', category: 'methodology', weight: 4, aliases: ['DevOps', 'Automation'] },
    { keyword: 'Code Quality', category: 'methodology', weight: 2, aliases: ['Linting', 'Static Analysis'] },
    { keyword: 'Documentation', category: 'methodology', weight: 2, aliases: ['Technical Writing'] },
    { keyword: 'Mentoring', category: 'methodology', weight: 2, aliases: ['Tech Lead', 'Leadership'] },
  ],

  'qa-engineer': [
    // Languages
    { keyword: 'Python', category: 'language', weight: 5, aliases: ['py'] },
    { keyword: 'JavaScript', category: 'language', weight: 4, aliases: ['JS'] },
    { keyword: 'TypeScript', category: 'language', weight: 3, aliases: ['TS'] },
    { keyword: 'Java', category: 'language', weight: 4, aliases: [] },
    { keyword: 'C#', category: 'language', weight: 2, aliases: ['CSharp'] },
    { keyword: 'Ruby', category: 'language', weight: 2, aliases: [] },
    { keyword: 'Kotlin', category: 'language', weight: 2, aliases: [] },
    { keyword: 'SQL', category: 'language', weight: 3, aliases: ['Structured Query Language'] },
    { keyword: 'Shell Script', category: 'language', weight: 2, aliases: ['Bash'] },
    // Frameworks
    { keyword: 'Selenium', category: 'framework', weight: 5, aliases: ['Selenium WebDriver'] },
    { keyword: 'Cypress', category: 'framework', weight: 5, aliases: [] },
    { keyword: 'Playwright', category: 'framework', weight: 4, aliases: [] },
    { keyword: 'Puppeteer', category: 'framework', weight: 3, aliases: [] },
    { keyword: 'Appium', category: 'framework', weight: 3, aliases: ['Mobile Testing'] },
    { keyword: 'JUnit', category: 'framework', weight: 4, aliases: ['TestNG'] },
    { keyword: 'pytest', category: 'framework', weight: 4, aliases: ['PyTest'] },
    { keyword: 'Jest', category: 'framework', weight: 4, aliases: [] },
    { keyword: 'Mocha', category: 'framework', weight: 3, aliases: ['Chai'] },
    { keyword: 'Cucumber', category: 'framework', weight: 3, aliases: ['BDD', 'Gherkin'] },
    { keyword: 'Rest Assured', category: 'framework', weight: 3, aliases: ['REST Assured'] },
    { keyword: 'Jasmine', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'Karma', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'Detox', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'MSTest', category: 'framework', weight: 2, aliases: [] },
    // Tools
    { keyword: 'Jenkins', category: 'tool', weight: 4, aliases: ['Jenkins Pipeline'] },
    { keyword: 'Docker', category: 'tool', weight: 3, aliases: ['Container'] },
    { keyword: 'Git', category: 'tool', weight: 4, aliases: ['GitHub', 'GitLab'] },
    { keyword: 'Jira', category: 'tool', weight: 4, aliases: ['Bug Tracking'] },
    { keyword: 'TestRail', category: 'tool', weight: 3, aliases: ['Test Case Management'] },
    { keyword: 'Postman', category: 'tool', weight: 5, aliases: ['API Testing'] },
    { keyword: 'JMeter', category: 'tool', weight: 3, aliases: ['Performance Testing'] },
    { keyword: 'Gatling', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'K6', category: 'tool', weight: 2, aliases: ['k6.io'] },
    { keyword: 'BrowserStack', category: 'tool', weight: 2, aliases: ['Cross Browser Testing'] },
    { keyword: 'Sauce Labs', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'Kubernetes', category: 'tool', weight: 2, aliases: ['K8s'] },
    { keyword: 'Swagger', category: 'tool', weight: 2, aliases: ['OpenAPI'] },
    { keyword: 'Charles Proxy', category: 'tool', weight: 2, aliases: ['Proxy'] },
    { keyword: 'Zephyr', category: 'tool', weight: 2, aliases: [] },
    // Databases
    { keyword: 'PostgreSQL', category: 'database', weight: 2, aliases: ['Postgres'] },
    { keyword: 'MySQL', category: 'database', weight: 2, aliases: [] },
    { keyword: 'MongoDB', category: 'database', weight: 2, aliases: ['Mongo'] },
    { keyword: 'SQL', category: 'database', weight: 3, aliases: ['Relational Database'] },
    // Concepts
    { keyword: 'Test Automation', category: 'concept', weight: 5, aliases: ['Automated Testing'] },
    { keyword: 'Manual Testing', category: 'concept', weight: 4, aliases: ['Exploratory Testing'] },
    { keyword: 'Regression Testing', category: 'concept', weight: 4, aliases: ['Regression'] },
    { keyword: 'Integration Testing', category: 'concept', weight: 4, aliases: ['Integration Test'] },
    { keyword: 'API Testing', category: 'concept', weight: 5, aliases: ['REST API Testing'] },
    { keyword: 'End-to-End Testing', category: 'concept', weight: 4, aliases: ['E2E Testing'] },
    { keyword: 'Performance Testing', category: 'concept', weight: 3, aliases: ['Load Testing', 'Stress Testing'] },
    { keyword: 'Security Testing', category: 'concept', weight: 2, aliases: ['Penetration Testing', 'Pen Testing'] },
    { keyword: 'Smoke Testing', category: 'concept', weight: 3, aliases: ['Sanity Testing'] },
    { keyword: 'Acceptance Testing', category: 'concept', weight: 3, aliases: ['UAT', 'User Acceptance Testing'] },
    { keyword: 'Test Planning', category: 'concept', weight: 3, aliases: ['Test Strategy', 'Test Plan'] },
    { keyword: 'Test Cases', category: 'concept', weight: 4, aliases: ['Test Case Design'] },
    { keyword: 'Bug Tracking', category: 'concept', weight: 3, aliases: ['Defect Tracking', 'Issue Tracking'] },
    { keyword: 'Test Data Management', category: 'concept', weight: 2, aliases: ['Test Data'] },
    { keyword: 'Cross-Browser Testing', category: 'concept', weight: 3, aliases: ['Cross Browser'] },
    { keyword: 'Mobile Testing', category: 'concept', weight: 3, aliases: ['Mobile App Testing'] },
    { keyword: 'White Box Testing', category: 'concept', weight: 2, aliases: [] },
    { keyword: 'Black Box Testing', category: 'concept', weight: 2, aliases: [] },
    { keyword: 'CI/CD', category: 'concept', weight: 3, aliases: ['Continuous Integration'] },
    { keyword: 'Page Object Model', category: 'concept', weight: 3, aliases: ['POM'] },
    { keyword: 'Data-Driven Testing', category: 'concept', weight: 3, aliases: ['DDT'] },
    { keyword: 'Behavior-Driven Development', category: 'concept', weight: 3, aliases: ['BDD'] },
    // Methodologies
    { keyword: 'Agile', category: 'methodology', weight: 4, aliases: ['Scrum', 'Sprint'] },
    { keyword: 'Quality Assurance', category: 'methodology', weight: 5, aliases: ['QA', 'Quality Control'] },
    { keyword: 'STLC', category: 'methodology', weight: 3, aliases: ['Software Testing Life Cycle'] },
    { keyword: 'Shift Left', category: 'methodology', weight: 2, aliases: ['Shift-Left Testing'] },
    { keyword: 'Risk-Based Testing', category: 'methodology', weight: 2, aliases: ['Risk Analysis'] },
  ],

  'frontend-developer': [
    // Languages
    { keyword: 'JavaScript', category: 'language', weight: 5, aliases: ['JS', 'ES6', 'ECMAScript'] },
    { keyword: 'TypeScript', category: 'language', weight: 5, aliases: ['TS'] },
    { keyword: 'HTML', category: 'language', weight: 5, aliases: ['HTML5'] },
    { keyword: 'CSS', category: 'language', weight: 5, aliases: ['CSS3', 'Cascading Style Sheets'] },
    { keyword: 'Sass', category: 'language', weight: 3, aliases: ['SCSS'] },
    { keyword: 'GraphQL', category: 'language', weight: 3, aliases: ['GraphQL API'] },
    // Frameworks
    { keyword: 'React', category: 'framework', weight: 5, aliases: ['React.js', 'ReactJS'] },
    { keyword: 'Next.js', category: 'framework', weight: 4, aliases: ['NextJS'] },
    { keyword: 'Vue.js', category: 'framework', weight: 3, aliases: ['Vue', 'VueJS', 'Nuxt'] },
    { keyword: 'Angular', category: 'framework', weight: 3, aliases: ['Angular 2+'] },
    { keyword: 'Redux', category: 'framework', weight: 4, aliases: ['Redux Toolkit', 'RTK'] },
    { keyword: 'Zustand', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'Tailwind CSS', category: 'framework', weight: 4, aliases: ['Tailwind'] },
    { keyword: 'Bootstrap', category: 'framework', weight: 3, aliases: ['Bootstrap 5'] },
    { keyword: 'Material UI', category: 'framework', weight: 3, aliases: ['MUI', 'Material-UI'] },
    { keyword: 'Chakra UI', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'Shadcn UI', category: 'framework', weight: 2, aliases: ['shadcn'] },
    { keyword: 'Framer Motion', category: 'framework', weight: 2, aliases: ['Animation'] },
    { keyword: 'Jest', category: 'framework', weight: 3, aliases: [] },
    { keyword: 'React Testing Library', category: 'framework', weight: 3, aliases: ['RTL'] },
    { keyword: 'Storybook', category: 'framework', weight: 2, aliases: [] },
    // Tools
    { keyword: 'Webpack', category: 'tool', weight: 3, aliases: ['Bundler'] },
    { keyword: 'Vite', category: 'tool', weight: 3, aliases: [] },
    { keyword: 'ESLint', category: 'tool', weight: 3, aliases: ['Linting'] },
    { keyword: 'Prettier', category: 'tool', weight: 2, aliases: ['Code Formatter'] },
    { keyword: 'Git', category: 'tool', weight: 4, aliases: ['GitHub', 'GitLab'] },
    { keyword: 'Chrome DevTools', category: 'tool', weight: 3, aliases: ['DevTools'] },
    { keyword: 'Figma', category: 'tool', weight: 2, aliases: ['Design'] },
    { keyword: 'npm', category: 'tool', weight: 2, aliases: ['yarn', 'pnpm'] },
    // Concepts
    { keyword: 'Responsive Design', category: 'concept', weight: 5, aliases: ['Responsive', 'Mobile-First'] },
    { keyword: 'Accessibility', category: 'concept', weight: 4, aliases: ['a11y', 'WCAG', 'Screen Reader'] },
    { keyword: 'Performance', category: 'concept', weight: 4, aliases: ['Web Vitals', 'Lighthouse', 'Performance Optimization'] },
    { keyword: 'SEO', category: 'concept', weight: 3, aliases: ['Search Engine Optimization'] },
    { keyword: 'Cross-Browser', category: 'concept', weight: 3, aliases: ['Browser Compatibility'] },
    { keyword: 'State Management', category: 'concept', weight: 4, aliases: ['State'] },
    { keyword: 'REST API', category: 'concept', weight: 4, aliases: ['REST', 'API Integration'] },
    { keyword: 'Component Library', category: 'concept', weight: 3, aliases: ['Design System', 'UI Components'] },
    { keyword: 'Progressive Web App', category: 'concept', weight: 2, aliases: ['PWA'] },
    { keyword: 'Server-Side Rendering', category: 'concept', weight: 3, aliases: ['SSR'] },
    { keyword: 'Static Site Generation', category: 'concept', weight: 2, aliases: ['SSG'] },
    { keyword: 'UI/UX', category: 'concept', weight: 3, aliases: ['User Experience', 'User Interface'] },
    { keyword: 'Animation', category: 'concept', weight: 2, aliases: ['CSS Animation', 'Transition'] },
    { keyword: 'Internationalization', category: 'concept', weight: 2, aliases: ['i18n'] },
    // Methodologies
    { keyword: 'Agile', category: 'methodology', weight: 2, aliases: ['Scrum'] },
    { keyword: 'Mobile-First', category: 'methodology', weight: 3, aliases: ['Mobile First Design'] },
    { keyword: 'Atomic Design', category: 'methodology', weight: 2, aliases: [] },
    { keyword: 'Testing', category: 'methodology', weight: 3, aliases: ['Unit Testing', 'Component Testing'] },
  ],

  'backend-developer': [
    // Languages
    { keyword: 'JavaScript', category: 'language', weight: 4, aliases: ['JS'] },
    { keyword: 'TypeScript', category: 'language', weight: 4, aliases: ['TS'] },
    { keyword: 'Python', category: 'language', weight: 5, aliases: ['py'] },
    { keyword: 'Java', category: 'language', weight: 5, aliases: [] },
    { keyword: 'Go', category: 'language', weight: 4, aliases: ['Golang'] },
    { keyword: 'Rust', category: 'language', weight: 2, aliases: [] },
    { keyword: 'C#', category: 'language', weight: 3, aliases: ['CSharp'] },
    { keyword: 'PHP', category: 'language', weight: 2, aliases: [] },
    { keyword: 'Ruby', category: 'language', weight: 2, aliases: [] },
    { keyword: 'Kotlin', category: 'language', weight: 2, aliases: [] },
    { keyword: 'SQL', category: 'language', weight: 5, aliases: ['Structured Query Language'] },
    { keyword: 'GraphQL', category: 'language', weight: 3, aliases: ['GQL'] },
    // Frameworks
    { keyword: 'Node.js', category: 'framework', weight: 5, aliases: ['Node', 'NodeJS'] },
    { keyword: 'Express', category: 'framework', weight: 5, aliases: ['Express.js'] },
    { keyword: 'NestJS', category: 'framework', weight: 3, aliases: ['Nest.js'] },
    { keyword: 'Spring Boot', category: 'framework', weight: 4, aliases: ['Spring', 'Spring Framework'] },
    { keyword: 'Django', category: 'framework', weight: 3, aliases: ['Django REST'] },
    { keyword: 'Flask', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'FastAPI', category: 'framework', weight: 3, aliases: [] },
    { keyword: 'ASP.NET', category: 'framework', weight: 3, aliases: ['.NET Core', 'DotNet'] },
    { keyword: 'Ruby on Rails', category: 'framework', weight: 2, aliases: ['Rails'] },
    { keyword: 'gRPC', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'REST API', category: 'framework', weight: 5, aliases: ['RESTful', 'REST APIs'] },
    // Tools
    { keyword: 'Docker', category: 'tool', weight: 5, aliases: ['Container', 'Containerization'] },
    { keyword: 'Kubernetes', category: 'tool', weight: 3, aliases: ['K8s'] },
    { keyword: 'Git', category: 'tool', weight: 4, aliases: ['GitHub', 'GitLab'] },
    { keyword: 'CI/CD', category: 'tool', weight: 4, aliases: ['Continuous Integration', 'Continuous Deployment'] },
    { keyword: 'AWS', category: 'tool', weight: 4, aliases: ['Amazon Web Services', 'EC2', 'Lambda'] },
    { keyword: 'Terraform', category: 'tool', weight: 2, aliases: ['IaC'] },
    { keyword: 'Nginx', category: 'tool', weight: 2, aliases: ['Reverse Proxy'] },
    { keyword: 'Postman', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'Swagger', category: 'tool', weight: 2, aliases: ['OpenAPI'] },
    // Databases
    { keyword: 'PostgreSQL', category: 'database', weight: 5, aliases: ['Postgres'] },
    { keyword: 'MySQL', category: 'database', weight: 4, aliases: [] },
    { keyword: 'MongoDB', category: 'database', weight: 4, aliases: ['Mongo'] },
    { keyword: 'Redis', category: 'database', weight: 4, aliases: ['Cache'] },
    { keyword: 'Elasticsearch', category: 'database', weight: 2, aliases: ['ES'] },
    { keyword: 'DynamoDB', category: 'database', weight: 2, aliases: ['Dynamo'] },
    { keyword: 'Cassandra', category: 'database', weight: 2, aliases: [] },
    { keyword: 'Memcached', category: 'database', weight: 2, aliases: [] },
    { keyword: 'Prisma', category: 'database', weight: 3, aliases: ['ORM'] },
    { keyword: 'TypeORM', category: 'database', weight: 2, aliases: [] },
    { keyword: 'Sequelize', category: 'database', weight: 2, aliases: [] },
    // Concepts
    { keyword: 'Microservices', category: 'concept', weight: 4, aliases: ['Service-Oriented'] },
    { keyword: 'API Design', category: 'concept', weight: 5, aliases: ['API Architecture'] },
    { keyword: 'Authentication', category: 'concept', weight: 4, aliases: ['Auth', 'OAuth', 'JWT', 'SSO'] },
    { keyword: 'Authorization', category: 'concept', weight: 3, aliases: ['RBAC', 'ACL'] },
    { keyword: 'Message Queue', category: 'concept', weight: 3, aliases: ['RabbitMQ', 'Kafka', 'Pub/Sub', 'Message Broker'] },
    { keyword: 'Caching', category: 'concept', weight: 4, aliases: ['Cache Strategy'] },
    { keyword: 'Load Balancing', category: 'concept', weight: 3, aliases: ['Load Balancer'] },
    { keyword: 'Database Optimization', category: 'concept', weight: 3, aliases: ['Query Optimization', 'Indexing'] },
    { keyword: 'System Design', category: 'concept', weight: 4, aliases: ['Architecture', 'Scalability'] },
    { keyword: 'WebSockets', category: 'concept', weight: 2, aliases: [] },
    { keyword: 'Rate Limiting', category: 'concept', weight: 2, aliases: [] },
    { keyword: 'Data Pipelines', category: 'concept', weight: 2, aliases: ['ETL', 'Data Processing'] },
    { keyword: 'Monitoring', category: 'concept', weight: 2, aliases: ['Observability', 'Logging'] },
    { keyword: 'Error Handling', category: 'concept', weight: 3, aliases: ['Exception Handling'] },
    // Methodologies
    { keyword: 'Agile', category: 'methodology', weight: 2, aliases: ['Scrum'] },
    { keyword: 'TDD', category: 'methodology', weight: 3, aliases: ['Test-Driven Development'] },
    { keyword: 'CI/CD', category: 'methodology', weight: 3, aliases: ['DevOps'] },
    { keyword: 'Database Migration', category: 'methodology', weight: 2, aliases: ['Schema Migration'] },
    { keyword: 'API Versioning', category: 'methodology', weight: 2, aliases: [] },
  ],

  'fullstack-developer': [
    { keyword: 'JavaScript', category: 'language', weight: 5, aliases: ['JS', 'ES6'] },
    { keyword: 'TypeScript', category: 'language', weight: 5, aliases: ['TS'] },
    { keyword: 'Python', category: 'language', weight: 3, aliases: [] },
    { keyword: 'HTML', category: 'language', weight: 5, aliases: ['HTML5'] },
    { keyword: 'CSS', category: 'language', weight: 5, aliases: ['CSS3'] },
    { keyword: 'SQL', category: 'language', weight: 4, aliases: [] },
    { keyword: 'GraphQL', category: 'language', weight: 3, aliases: [] },
    { keyword: 'React', category: 'framework', weight: 5, aliases: ['React.js', 'ReactJS'] },
    { keyword: 'Next.js', category: 'framework', weight: 4, aliases: ['NextJS'] },
    { keyword: 'Node.js', category: 'framework', weight: 5, aliases: ['Node', 'NodeJS'] },
    { keyword: 'Express', category: 'framework', weight: 4, aliases: ['Express.js'] },
    { keyword: 'NestJS', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'Django', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'Tailwind CSS', category: 'framework', weight: 3, aliases: ['Tailwind'] },
    { keyword: 'Bootstrap', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'Redux', category: 'framework', weight: 3, aliases: ['Redux Toolkit'] },
    { keyword: 'REST API', category: 'framework', weight: 5, aliases: ['RESTful'] },
    { keyword: 'Docker', category: 'tool', weight: 4, aliases: ['Container'] },
    { keyword: 'Git', category: 'tool', weight: 5, aliases: ['GitHub', 'GitLab'] },
    { keyword: 'CI/CD', category: 'tool', weight: 3, aliases: [] },
    { keyword: 'AWS', category: 'tool', weight: 3, aliases: ['Amazon Web Services'] },
    { keyword: 'PostgreSQL', category: 'database', weight: 4, aliases: ['Postgres'] },
    { keyword: 'MongoDB', category: 'database', weight: 3, aliases: ['Mongo'] },
    { keyword: 'Redis', category: 'database', weight: 2, aliases: [] },
    { keyword: 'Microservices', category: 'concept', weight: 3, aliases: [] },
    { keyword: 'Authentication', category: 'concept', weight: 4, aliases: ['Auth', 'JWT'] },
    { keyword: 'Authorization', category: 'concept', weight: 3, aliases: [] },
    { keyword: 'Responsive Design', category: 'concept', weight: 4, aliases: ['Mobile-Friendly'] },
    { keyword: 'API Design', category: 'concept', weight: 4, aliases: [] },
    { keyword: 'Testing', category: 'concept', weight: 3, aliases: ['Unit Test', 'Integration Test'] },
    { keyword: 'System Design', category: 'concept', weight: 3, aliases: ['Architecture'] },
    { keyword: 'Agile', category: 'methodology', weight: 2, aliases: ['Scrum'] },
    { keyword: 'Full Stack', category: 'concept', weight: 3, aliases: ['Full-Stack', 'Fullstack'] },
    { keyword: 'Frontend', category: 'concept', weight: 3, aliases: ['Client-Side'] },
    { keyword: 'Backend', category: 'concept', weight: 3, aliases: ['Server-Side'] },
    { keyword: 'Database Design', category: 'concept', weight: 3, aliases: ['Data Modeling'] },
    { keyword: 'Deployment', category: 'concept', weight: 3, aliases: ['Hosting', 'Release'] },
  ],

  'devops-engineer': [
    // Languages
    { keyword: 'Python', category: 'language', weight: 4, aliases: ['py'] },
    { keyword: 'Go', category: 'language', weight: 3, aliases: ['Golang'] },
    { keyword: 'Shell Script', category: 'language', weight: 5, aliases: ['Bash', 'Shell'] },
    { keyword: 'PowerShell', category: 'language', weight: 2, aliases: ['PS'] },
    { keyword: 'Ruby', category: 'language', weight: 2, aliases: [] },
    { keyword: 'HCL', category: 'language', weight: 3, aliases: ['Terraform', 'Hashicorp'] },
    // Tools
    { keyword: 'Docker', category: 'tool', weight: 5, aliases: ['Container', 'Containerization'] },
    { keyword: 'Kubernetes', category: 'tool', weight: 5, aliases: ['K8s', 'Kube'] },
    { keyword: 'Terraform', category: 'tool', weight: 5, aliases: ['IaC', 'Infrastructure as Code'] },
    { keyword: 'Ansible', category: 'tool', weight: 4, aliases: ['Configuration Management'] },
    { keyword: 'Puppet', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'Chef', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'Jenkins', category: 'tool', weight: 4, aliases: ['Jenkins Pipeline'] },
    { keyword: 'GitHub Actions', category: 'tool', weight: 4, aliases: ['GHA', 'Actions'] },
    { keyword: 'GitLab CI', category: 'tool', weight: 3, aliases: ['GitLab CI/CD'] },
    { keyword: 'CircleCI', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'ArgoCD', category: 'tool', weight: 3, aliases: ['GitOps', 'Argo'] },
    { keyword: 'Helm', category: 'tool', weight: 3, aliases: ['Helm Charts'] },
    { keyword: 'Prometheus', category: 'tool', weight: 4, aliases: ['Monitoring'] },
    { keyword: 'Grafana', category: 'tool', weight: 4, aliases: ['Dashboards'] },
    { keyword: 'ELK Stack', category: 'tool', weight: 3, aliases: ['Elasticsearch', 'Logstash', 'Kibana', 'Elastic Stack'] },
    { keyword: 'Datadog', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'New Relic', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'Git', category: 'tool', weight: 4, aliases: ['GitHub', 'GitLab'] },
    { keyword: 'Nginx', category: 'tool', weight: 3, aliases: ['Reverse Proxy', 'Web Server'] },
    { keyword: 'Traefik', category: 'tool', weight: 2, aliases: ['Ingress'] },
    { keyword: 'Vault', category: 'tool', weight: 2, aliases: ['Secrets Management'] },
    { keyword: 'Consul', category: 'tool', weight: 2, aliases: ['Service Discovery'] },
    { keyword: 'Packer', category: 'tool', weight: 2, aliases: ['Image Builder'] },
    { keyword: 'Vagrant', category: 'tool', weight: 1, aliases: [] },
    // Cloud Providers
    { keyword: 'AWS', category: 'cloud', weight: 5, aliases: ['Amazon Web Services', 'EC2', 'S3', 'Lambda', 'ECS', 'EKS'] },
    { keyword: 'Azure', category: 'cloud', weight: 4, aliases: ['Microsoft Azure', 'AKS'] },
    { keyword: 'GCP', category: 'cloud', weight: 4, aliases: ['Google Cloud', 'Google Cloud Platform', 'GKE'] },
    // Concepts
    { keyword: 'CI/CD', category: 'concept', weight: 5, aliases: ['Continuous Integration', 'Continuous Deployment', 'Continuous Delivery'] },
    { keyword: 'Infrastructure as Code', category: 'concept', weight: 5, aliases: ['IaC'] },
    { keyword: 'Containerization', category: 'concept', weight: 5, aliases: ['Containers'] },
    { keyword: 'Orchestration', category: 'concept', weight: 4, aliases: ['Container Orchestration'] },
    { keyword: 'Microservices', category: 'concept', weight: 4, aliases: [] },
    { keyword: 'Monitoring', category: 'concept', weight: 4, aliases: ['Observability', 'Telemetry'] },
    { keyword: 'Logging', category: 'concept', weight: 3, aliases: ['Log Management'] },
    { keyword: 'Alerting', category: 'concept', weight: 3, aliases: ['Alerts', 'Incident Response'] },
    { keyword: 'Networking', category: 'concept', weight: 3, aliases: ['Network', 'DNS', 'TCP/IP'] },
    { keyword: 'Security', category: 'concept', weight: 4, aliases: ['DevSecOps', 'Security Best Practices'] },
    { keyword: 'High Availability', category: 'concept', weight: 3, aliases: ['HA', 'Redundancy'] },
    { keyword: 'Disaster Recovery', category: 'concept', weight: 2, aliases: ['DR', 'Backup'] },
    { keyword: 'Scaling', category: 'concept', weight: 3, aliases: ['Auto Scaling', 'Horizontal Scaling', 'Vertical Scaling'] },
    { keyword: 'Load Balancing', category: 'concept', weight: 3, aliases: ['Load Balancer'] },
    { keyword: 'Secrets Management', category: 'concept', weight: 3, aliases: ['Secrets'] },
    { keyword: 'Service Mesh', category: 'concept', weight: 2, aliases: ['Istio', 'Linkerd'] },
    // Methodologies
    { keyword: 'Agile', category: 'methodology', weight: 2, aliases: ['Scrum'] },
    { keyword: 'DevOps', category: 'methodology', weight: 5, aliases: ['Dev Ops'] },
    { keyword: 'SRE', category: 'methodology', weight: 2, aliases: ['Site Reliability Engineering'] },
    { keyword: 'GitOps', category: 'methodology', weight: 3, aliases: [] },
    { keyword: 'Chaos Engineering', category: 'methodology', weight: 2, aliases: [] },
    { keyword: 'Automation', category: 'methodology', weight: 4, aliases: ['Automate'] },
  ],

  'data-scientist': [
    // Languages
    { keyword: 'Python', category: 'language', weight: 5, aliases: ['py'] },
    { keyword: 'R', category: 'language', weight: 4, aliases: ['R Stats'] },
    { keyword: 'SQL', category: 'language', weight: 5, aliases: ['Structured Query Language'] },
    { keyword: 'Julia', category: 'language', weight: 1, aliases: [] },
    { keyword: 'Scala', category: 'language', weight: 2, aliases: [] },
    { keyword: 'Java', category: 'language', weight: 2, aliases: [] },
    { keyword: 'MATLAB', category: 'language', weight: 1, aliases: [] },
    // Libraries & Frameworks
    { keyword: 'TensorFlow', category: 'framework', weight: 5, aliases: ['TF', 'Tensorflow'] },
    { keyword: 'PyTorch', category: 'framework', weight: 5, aliases: ['Torch'] },
    { keyword: 'scikit-learn', category: 'framework', weight: 5, aliases: ['sklearn'] },
    { keyword: 'Pandas', category: 'framework', weight: 5, aliases: ['pandas'] },
    { keyword: 'NumPy', category: 'framework', weight: 4, aliases: ['numpy'] },
    { keyword: 'Matplotlib', category: 'framework', weight: 3, aliases: ['plotting'] },
    { keyword: 'Seaborn', category: 'framework', weight: 2, aliases: [] },
    { keyword: 'Plotly', category: 'framework', weight: 2, aliases: ['Dash'] },
    { keyword: 'XGBoost', category: 'framework', weight: 3, aliases: ['XGB'] },
    { keyword: 'LightGBM', category: 'framework', weight: 2, aliases: ['LGBM'] },
    { keyword: 'Jupyter', category: 'framework', weight: 4, aliases: ['Jupyter Notebook', 'JupyterLab'] },
    { keyword: 'LangChain', category: 'framework', weight: 3, aliases: ['LLM', 'Langchain'] },
    { keyword: 'Hugging Face', category: 'framework', weight: 3, aliases: ['Transformers', 'Huggingface'] },
    { keyword: 'Spark MLlib', category: 'framework', weight: 2, aliases: ['Spark ML'] },
    // Tools
    { keyword: 'Docker', category: 'tool', weight: 2, aliases: ['Container'] },
    { keyword: 'Git', category: 'tool', weight: 3, aliases: ['GitHub'] },
    { keyword: 'MLflow', category: 'tool', weight: 3, aliases: ['Experiment Tracking'] },
    { keyword: 'Kubeflow', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'Airflow', category: 'tool', weight: 3, aliases: ['DAG', 'Pipeline Orchestration'] },
    { keyword: 'AWS SageMaker', category: 'tool', weight: 2, aliases: ['SageMaker'] },
    // Concepts
    { keyword: 'Machine Learning', category: 'concept', weight: 5, aliases: ['ML', 'Machine Learning Models'] },
    { keyword: 'Deep Learning', category: 'concept', weight: 4, aliases: ['DL', 'Neural Networks'] },
    { keyword: 'Natural Language Processing', category: 'concept', weight: 4, aliases: ['NLP'] },
    { keyword: 'Computer Vision', category: 'concept', weight: 3, aliases: ['CV'] },
    { keyword: 'Statistics', category: 'concept', weight: 5, aliases: ['Statistical Analysis', 'Stats'] },
    { keyword: 'Probability', category: 'concept', weight: 3, aliases: [] },
    { keyword: 'Linear Algebra', category: 'concept', weight: 3, aliases: [] },
    { keyword: 'Calculus', category: 'concept', weight: 2, aliases: [] },
    { keyword: 'Feature Engineering', category: 'concept', weight: 4, aliases: ['Feature Extraction'] },
    { keyword: 'Feature Selection', category: 'concept', weight: 3, aliases: [] },
    { keyword: 'Model Deployment', category: 'concept', weight: 3, aliases: ['MLOps', 'Model Serving'] },
    { keyword: 'A/B Testing', category: 'concept', weight: 3, aliases: ['Hypothesis Testing'] },
    { keyword: 'Experiment Design', category: 'concept', weight: 3, aliases: ['Experimental Design'] },
    { keyword: 'Data Wrangling', category: 'concept', weight: 4, aliases: ['Data Cleaning', 'Data Preprocessing'] },
    { keyword: 'Data Visualization', category: 'concept', weight: 4, aliases: ['Data Viz', 'Visualization'] },
    { keyword: 'Time Series', category: 'concept', weight: 3, aliases: ['Time Series Analysis', 'Forecasting'] },
    { keyword: 'Regression', category: 'concept', weight: 3, aliases: ['Linear Regression', 'Logistic Regression'] },
    { keyword: 'Classification', category: 'concept', weight: 3, aliases: ['Classifier'] },
    { keyword: 'Clustering', category: 'concept', weight: 3, aliases: ['Unsupervised Learning'] },
    { keyword: 'Reinforcement Learning', category: 'concept', weight: 2, aliases: ['RL'] },
    { keyword: 'Dimensionality Reduction', category: 'concept', weight: 2, aliases: ['PCA', 't-SNE'] },
    { keyword: 'Model Evaluation', category: 'concept', weight: 3, aliases: ['Cross-Validation', 'ROC', 'AUC'] },
    { keyword: 'Bias-Variance Tradeoff', category: 'concept', weight: 2, aliases: ['Overfitting', 'Underfitting'] },
    { keyword: 'Big Data', category: 'concept', weight: 3, aliases: ['Large Scale Data'] },
    { keyword: 'ETL', category: 'concept', weight: 3, aliases: ['Data Pipeline', 'Data Processing'] },
  ],

  'data-engineer': [
    // Languages
    { keyword: 'Python', category: 'language', weight: 5, aliases: ['py'] },
    { keyword: 'SQL', category: 'language', weight: 5, aliases: ['Structured Query Language'] },
    { keyword: 'Java', category: 'language', weight: 3, aliases: [] },
    { keyword: 'Scala', category: 'language', weight: 3, aliases: [] },
    { keyword: 'Shell Script', category: 'language', weight: 2, aliases: ['Bash'] },
    { keyword: 'Go', category: 'language', weight: 2, aliases: [] },
    // Frameworks
    { keyword: 'Apache Spark', category: 'framework', weight: 5, aliases: ['Spark'] },
    { keyword: 'Apache Kafka', category: 'framework', weight: 4, aliases: ['Kafka'] },
    { keyword: 'Apache Flink', category: 'framework', weight: 2, aliases: ['Flink'] },
    { keyword: 'Apache Hadoop', category: 'framework', weight: 3, aliases: ['Hadoop', 'HDFS'] },
    { keyword: 'Apache Airflow', category: 'framework', weight: 4, aliases: ['Airflow', 'DAG'] },
    { keyword: 'dbt', category: 'framework', weight: 3, aliases: ['Data Build Tool'] },
    { keyword: 'Pandas', category: 'framework', weight: 3, aliases: [] },
    { keyword: 'Spark SQL', category: 'framework', weight: 3, aliases: [] },
    // Tools
    { keyword: 'Docker', category: 'tool', weight: 3, aliases: [] },
    { keyword: 'Git', category: 'tool', weight: 3, aliases: ['GitHub', 'GitLab'] },
    { keyword: 'Terraform', category: 'tool', weight: 2, aliases: [] },
    { keyword: 'Kubernetes', category: 'tool', weight: 2, aliases: ['K8s'] },
    // Cloud Data Platforms
    { keyword: 'BigQuery', category: 'cloud', weight: 4, aliases: ['Google BigQuery'] },
    { keyword: 'Redshift', category: 'cloud', weight: 4, aliases: ['Amazon Redshift'] },
    { keyword: 'Snowflake', category: 'cloud', weight: 4, aliases: [] },
    { keyword: 'Databricks', category: 'cloud', weight: 3, aliases: [] },
    { keyword: 'AWS Glue', category: 'cloud', weight: 3, aliases: ['Glue'] },
    { keyword: 'Azure Data Factory', category: 'cloud', weight: 2, aliases: ['ADF'] },
    // Databases
    { keyword: 'PostgreSQL', category: 'database', weight: 4, aliases: ['Postgres'] },
    { keyword: 'MySQL', category: 'database', weight: 3, aliases: [] },
    { keyword: 'MongoDB', category: 'database', weight: 2, aliases: [] },
    { keyword: 'Cassandra', category: 'database', weight: 2, aliases: [] },
    { keyword: 'Elasticsearch', category: 'database', weight: 2, aliases: [] },
    // Concepts
    { keyword: 'Data Pipeline', category: 'concept', weight: 5, aliases: ['ETL', 'ELT', 'Data Processing'] },
    { keyword: 'Data Warehousing', category: 'concept', weight: 4, aliases: ['Data Warehouse'] },
    { keyword: 'Data Lake', category: 'concept', weight: 3, aliases: ['Data Lakehouse'] },
    { keyword: 'Data Modeling', category: 'concept', weight: 4, aliases: ['Dimensional Modeling', 'Star Schema'] },
    { keyword: 'Streaming Data', category: 'concept', weight: 3, aliases: ['Real-Time', 'Stream Processing'] },
    { keyword: 'Batch Processing', category: 'concept', weight: 3, aliases: ['Batch'] },
    { keyword: 'Data Quality', category: 'concept', weight: 3, aliases: ['Data Validation', 'Data Testing'] },
    { keyword: 'Data Governance', category: 'concept', weight: 2, aliases: ['Data Catalog', 'Data Lineage'] },
    { keyword: 'Schema Design', category: 'concept', weight: 3, aliases: ['Schema Evolution'] },
    { keyword: 'Partitioning', category: 'concept', weight: 3, aliases: ['Data Partitioning'] },
    { keyword: 'Data Migration', category: 'concept', weight: 2, aliases: [] },
    { keyword: 'OLAP', category: 'concept', weight: 2, aliases: ['OLAP Cube'] },
    { keyword: 'Big Data', category: 'concept', weight: 4, aliases: ['Large Scale Data'] },
    { keyword: 'Data Architecture', category: 'concept', weight: 3, aliases: ['Data Infrastructure'] },
    { keyword: 'Scalability', category: 'concept', weight: 3, aliases: ['Scaling'] },
    { keyword: 'Performance Optimization', category: 'concept', weight: 3, aliases: ['Query Optimization'] },
  ],

  'product-manager': [
    // Tools
    { keyword: 'Jira', category: 'tool', weight: 5, aliases: ['JIRA', 'Project Management'] },
    { keyword: 'Confluence', category: 'tool', weight: 3, aliases: ['Wiki'] },
    { keyword: 'Figma', category: 'tool', weight: 3, aliases: ['Wireframe', 'Design Tool'] },
    { keyword: 'Miro', category: 'tool', weight: 2, aliases: ['Whiteboard'] },
    { keyword: 'Notion', category: 'tool', weight: 2, aliases: ['Documentation'] },
    { keyword: 'Amplitude', category: 'tool', weight: 3, aliases: ['Analytics'] },
    { keyword: 'Mixpanel', category: 'tool', weight: 2, aliases: ['Product Analytics'] },
    { keyword: 'Google Analytics', category: 'tool', weight: 3, aliases: ['GA'] },
    { keyword: 'Tableau', category: 'tool', weight: 2, aliases: ['Data Visualization'] },
    { keyword: 'SQL', category: 'tool', weight: 3, aliases: ['Structured Query Language'] },
    { keyword: 'Aha!', category: 'tool', weight: 1, aliases: ['Roadmapping'] },
    { keyword: 'Productboard', category: 'tool', weight: 2, aliases: ['Product Management'] },
    { keyword: 'Trello', category: 'tool', weight: 1, aliases: ['Kanban'] },
    { keyword: 'Asana', category: 'tool', weight: 1, aliases: [] },
    { keyword: 'Pendo', category: 'tool', weight: 2, aliases: ['User Analytics'] },
    { keyword: 'Hotjar', category: 'tool', weight: 2, aliases: ['User Feedback'] },
    { keyword: 'Intercom', category: 'tool', weight: 2, aliases: ['Customer Communication'] },
    { keyword: 'GitHub', category: 'tool', weight: 2, aliases: ['Git', 'Version Control'] },
    // Concepts
    { keyword: 'Product Strategy', category: 'concept', weight: 5, aliases: ['Product Vision', 'Strategy'] },
    { keyword: 'Roadmap', category: 'concept', weight: 4, aliases: ['Product Roadmap', 'Release Plan'] },
    { keyword: 'User Stories', category: 'concept', weight: 4, aliases: ['Story', 'Epic'] },
    { keyword: 'Backlog Management', category: 'concept', weight: 4, aliases: ['Backlog Grooming', 'Backlog Refinement'] },
    { keyword: 'Requirements Gathering', category: 'concept', weight: 4, aliases: ['Requirements', 'Business Requirements'] },
    { keyword: 'Stakeholder Management', category: 'concept', weight: 4, aliases: ['Stakeholder Communication'] },
    { keyword: 'User Research', category: 'concept', weight: 4, aliases: ['User Interviews', 'UX Research'] },
    { keyword: 'A/B Testing', category: 'concept', weight: 3, aliases: ['Split Testing', 'Experimentation'] },
    { keyword: 'Market Research', category: 'concept', weight: 3, aliases: ['Market Analysis', 'Competitive Analysis'] },
    { keyword: 'Data-Driven', category: 'concept', weight: 4, aliases: ['Data Informed', 'Metrics-Driven'] },
    { keyword: 'KPI', category: 'concept', weight: 4, aliases: ['OKR', 'Metrics', 'Key Performance Indicators'] },
    { keyword: 'Wireframing', category: 'concept', weight: 3, aliases: ['Prototyping', 'Mockups'] },
    { keyword: 'Product Launch', category: 'concept', weight: 3, aliases: ['Go-to-Market', 'GTM', 'Release'] },
    { keyword: 'Customer Journey', category: 'concept', weight: 3, aliases: ['User Journey', 'User Flow'] },
    { keyword: 'Persona', category: 'concept', weight: 2, aliases: ['User Persona', 'Buyer Persona'] },
    { keyword: 'Retention', category: 'concept', weight: 3, aliases: ['User Retention', 'Churn'] },
    { keyword: 'Conversion', category: 'concept', weight: 3, aliases: ['Conversion Rate', 'CRO'] },
    { keyword: 'NPS', category: 'concept', weight: 2, aliases: ['Net Promoter Score', 'CSAT'] },
    { keyword: 'Prioritization', category: 'concept', weight: 4, aliases: ['RICE', 'ICE', 'MoSCoW'] },
    { keyword: 'Feature Prioritization', category: 'concept', weight: 3, aliases: ['Feature Selection'] },
    { keyword: 'Technical Debt', category: 'concept', weight: 2, aliases: ['Tech Debt'] },
    { keyword: 'Agile', category: 'concept', weight: 4, aliases: ['Scrum', 'Sprint Planning', 'Stand-up'] },
    { keyword: 'Lean', category: 'concept', weight: 2, aliases: ['Lean Startup', 'MVP'] },
    { keyword: 'PRD', category: 'concept', weight: 3, aliases: ['Product Requirements Document', 'Spec'] },
    // Methodologies
    { keyword: 'Agile Methodology', category: 'methodology', weight: 5, aliases: ['Agile', 'Scrum', 'Kanban'] },
    { keyword: 'Design Thinking', category: 'methodology', weight: 3, aliases: ['Human-Centered Design'] },
    { keyword: 'Lean Startup', category: 'methodology', weight: 2, aliases: ['Build-Measure-Learn'] },
    { keyword: 'Cross-functional Leadership', category: 'methodology', weight: 3, aliases: ['Cross-team Collaboration'] },
    { keyword: 'Strategic Planning', category: 'methodology', weight: 3, aliases: ['Strategic Thinking'] },
    { keyword: 'Communication', category: 'methodology', weight: 3, aliases: ['Presentation', 'Public Speaking'] },
    { keyword: 'Negotiation', category: 'methodology', weight: 2, aliases: ['Conflict Resolution'] },
  ],
};

async function main() {
  console.log('Seeding role keywords...');

  for (const [role, keywords] of Object.entries(ROLE_KEYWORD_MAP)) {
    for (const entry of keywords) {
      await prisma.roleKeyword.create({
        data: {
          role,
          category: entry.category,
          keyword: entry.keyword,
          weight: entry.weight,
          aliases: entry.aliases,
        },
      });
    }
    console.log(`  ✓ ${role}: ${keywords.length} keywords`);
  }

  const total = Object.values(ROLE_KEYWORD_MAP).reduce((sum, k) => sum + k.length, 0);
  console.log(`\n✅ Total: ${total} keywords seeded across ${Object.keys(ROLE_KEYWORD_MAP).length} roles`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
